services:
  postgres:
    image: postgres:15.7
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=4Dm1nDB*
      - POSTGRES_USER=admin
      - POSTGRES_DB=test_db
      - TZ=America/Bogota  # Añade esta línea para la zona horaria de Colombia
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - red_local_postgres

networks:
  red_local_postgres:
    driver: bridge